import type { Metadata } from "next";
import * as C from "@/components/index"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <C.Header />
        <C.Hero />
        {children}
        <C.Footer />
      </body>
    </html>
  );
}
